version: '3.8'

services:
  frontend:
    build: ./frontend
    container_name: group11-frontend
    ports:
      - "3000:3000"
    environment:
      # 關鍵：讓前端網頁瀏覽器知道，API 請求一律打給 VM1 (Load Balancer)
      - NEXT_PUBLIC_API_URL=http://192.168.10.1:8000 
    restart: unless-stopped