services:
  frontend:
    # 告訴 Compose 去 frontend 資料夾找 Dockerfile 來 Build
    build: ./frontend
    container_name: group11-frontend
    ports:
      - "3000:3000"

  backend:
    # 告訴 Compose 去 backend 資料夾找 Dockerfile 來 Build
    build: ./backend
    container_name: group11-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app  # 把本地程式碼掛載進去，方便開發
      - ./logs:/app/logs
    env_file:
      - ./backend/.env
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - LOG_ROOT=/app/logs
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  prometheus:
    image: prom/prometheus:latest
    container_name: group11-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      backend:
        condition: service_started

  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=k6

  grafana:
    image: grafana/grafana:latest
    container_name: group11-grafana
    ports:
      - "3001:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./monitoring/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    depends_on:
      - prometheus

  backend-worker:
    build:
      context: ./backend
      dockerfile: Dockerfile.worker
    #container_name: group11-worker
    volumes:
      - ./backend:/app
      - ./logs:/app/logs
    env_file:
      - ./backend/.env
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PYTHONPATH=/app
      - LOG_ROOT=/app/logs
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    restart: always

  backend-scheduler:
    build:
      context: ./backend
      dockerfile: Dockerfile.worker
    container_name: group11-scheduler
    command: ["python", "src/scheduler/cron_scheduler.py"]
    volumes:
      - ./backend:/app
      - ./logs:/app/logs
    env_file:
      - ./backend/.env
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PYTHONPATH=/app
      - LOG_ROOT=/app/logs
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    restart: always

  redis:
    image: redis:7-alpine
    container_name: group11-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  db:
    image: mysql:8.4
    container_name: group11-mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    env_file:
      - ./backend/.env
    environment:
      TZ: Asia/Taipei
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data:
  redis_data:
  grafana_data:
